/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: trace/Tracing.proto

package io.holoinsight.server.apm.grpc.trace;

/**
 * <pre>
 * Map to the type of span
 * </pre>
 *
 * Protobuf enum {@code io.holoinsight.server.apm.grpc.trace.SpanType}
 */
public enum SpanType implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Server side of RPC. Consumer side of MQ.
   * </pre>
   *
   * <code>Entry = 0;</code>
   */
  Entry(0),
  /**
   * <pre>
   * Client side of RPC. Producer side of MQ.
   * </pre>
   *
   * <code>Exit = 1;</code>
   */
  Exit(1),
  /**
   * <pre>
   * A common local code execution.
   * </pre>
   *
   * <code>Local = 2;</code>
   */
  Local(2), UNRECOGNIZED(-1),;

  /**
   * <pre>
   * Server side of RPC. Consumer side of MQ.
   * </pre>
   *
   * <code>Entry = 0;</code>
   */
  public static final int Entry_VALUE = 0;
  /**
   * <pre>
   * Client side of RPC. Producer side of MQ.
   * </pre>
   *
   * <code>Exit = 1;</code>
   */
  public static final int Exit_VALUE = 1;
  /**
   * <pre>
   * A common local code execution.
   * </pre>
   *
   * <code>Local = 2;</code>
   */
  public static final int Local_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SpanType valueOf(int value) {
    return forNumber(value);
  }

  public static SpanType forNumber(int value) {
    switch (value) {
      case 0:
        return Entry;
      case 1:
        return Exit;
      case 2:
        return Local;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SpanType> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<SpanType> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<SpanType>() {
        public SpanType findValueByNumber(int number) {
          return SpanType.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
    return getDescriptor();
  }

  public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
    return io.holoinsight.server.apm.grpc.trace.Tracing.getDescriptor().getEnumTypes().get(0);
  }

  private static final SpanType[] VALUES = values();

  public static SpanType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SpanType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.holoinsight.server.apm.grpc.trace.SpanType)
}

