/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common/Common.proto

package io.holoinsight.server.apm.grpc.common;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.apm.grpc.common.CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 具体每个code是什么含义由每个业务自己定
   * 但规定 code == 0 表示业务成功
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();

  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString getMessageBytes();
}
