/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common/Common.proto

package io.holoinsight.server.apm.grpc.common;

public interface CommandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.apm.grpc.common.Commands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.holoinsight.server.apm.grpc.common.Command commands = 1;</code>
   */
  java.util.List<io.holoinsight.server.apm.grpc.common.Command> getCommandsList();

  /**
   * <code>repeated .io.holoinsight.server.apm.grpc.common.Command commands = 1;</code>
   */
  io.holoinsight.server.apm.grpc.common.Command getCommands(int index);

  /**
   * <code>repeated .io.holoinsight.server.apm.grpc.common.Command commands = 1;</code>
   */
  int getCommandsCount();

  /**
   * <code>repeated .io.holoinsight.server.apm.grpc.common.Command commands = 1;</code>
   */
  java.util.List<? extends io.holoinsight.server.apm.grpc.common.CommandOrBuilder> getCommandsOrBuilderList();

  /**
   * <code>repeated .io.holoinsight.server.apm.grpc.common.Command commands = 1;</code>
   */
  io.holoinsight.server.apm.grpc.common.CommandOrBuilder getCommandsOrBuilder(int index);
}
