/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common/Common.proto

package io.holoinsight.server.apm.grpc.common;

public interface CPUOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.apm.grpc.common.CPU)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double usagePercent = 2;</code>
   */
  double getUsagePercent();
}
