/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: AlarmService.proto

package io.holoinsight.server.home.proto.alarm;

/**
 * Protobuf type {@code QueryAlarmHistoryPageRequest}
 */
public final class QueryAlarmHistoryPageRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:QueryAlarmHistoryPageRequest)
    QueryAlarmHistoryPageRequestOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use QueryAlarmHistoryPageRequest.newBuilder() to construct.
  private QueryAlarmHistoryPageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private QueryAlarmHistoryPageRequest() {
    tenant_ = "";
    rowsJson_ = "";
    traceId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private QueryAlarmHistoryPageRequest(com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            tenant_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            rowsJson_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            traceId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.holoinsight.server.home.proto.alarm.AlarmServiceProto.internal_static_QueryAlarmHistoryPageRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
    return io.holoinsight.server.home.proto.alarm.AlarmServiceProto.internal_static_QueryAlarmHistoryPageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest.class,
            io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest.Builder.class);
  }

  public static final int TENANT_FIELD_NUMBER = 1;
  private volatile Object tenant_;

  /**
   * <code>string tenant = 1;</code>
   */
  public String getTenant() {
    Object ref = tenant_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tenant_ = s;
      return s;
    }
  }

  /**
   * <code>string tenant = 1;</code>
   */
  public com.google.protobuf.ByteString getTenantBytes() {
    Object ref = tenant_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      tenant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROWSJSON_FIELD_NUMBER = 2;
  private volatile Object rowsJson_;

  /**
   * <code>string rowsJson = 2;</code>
   */
  public String getRowsJson() {
    Object ref = rowsJson_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      rowsJson_ = s;
      return s;
    }
  }

  /**
   * <code>string rowsJson = 2;</code>
   */
  public com.google.protobuf.ByteString getRowsJsonBytes() {
    Object ref = rowsJson_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      rowsJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACEID_FIELD_NUMBER = 3;
  private volatile Object traceId_;

  /**
   * <code>string traceId = 3;</code>
   */
  public String getTraceId() {
    Object ref = traceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }

  /**
   * <code>string traceId = 3;</code>
   */
  public com.google.protobuf.ByteString getTraceIdBytes() {
    Object ref = traceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getTenantBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tenant_);
    }
    if (!getRowsJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rowsJson_);
    }
    if (!getTraceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, traceId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (!getTenantBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tenant_);
    }
    if (!getRowsJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rowsJson_);
    }
    if (!getTraceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, traceId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest)) {
      return super.equals(obj);
    }
    io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest other =
        (io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest) obj;

    boolean result = true;
    result = result && getTenant().equals(other.getTenant());
    result = result && getRowsJson().equals(other.getRowsJson());
    result = result && getTraceId().equals(other.getTraceId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_FIELD_NUMBER;
    hash = (53 * hash) + getTenant().hashCode();
    hash = (37 * hash) + ROWSJSON_FIELD_NUMBER;
    hash = (53 * hash) + getRowsJson().hashCode();
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code QueryAlarmHistoryPageRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:QueryAlarmHistoryPageRequest)
      io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.holoinsight.server.home.proto.alarm.AlarmServiceProto.internal_static_QueryAlarmHistoryPageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return io.holoinsight.server.home.proto.alarm.AlarmServiceProto.internal_static_QueryAlarmHistoryPageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest.class,
              io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest.Builder.class);
    }

    // Construct using
    // io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
      }
    }

    public Builder clear() {
      super.clear();
      tenant_ = "";

      rowsJson_ = "";

      traceId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.holoinsight.server.home.proto.alarm.AlarmServiceProto.internal_static_QueryAlarmHistoryPageRequest_descriptor;
    }

    public io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest getDefaultInstanceForType() {
      return io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest
          .getDefaultInstance();
    }

    public io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest build() {
      io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest buildPartial() {
      io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest result =
          new io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest(this);
      result.tenant_ = tenant_;
      result.rowsJson_ = rowsJson_;
      result.traceId_ = traceId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }

    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return (Builder) super.setField(field, value);
    }

    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }

    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }

    public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest) {
        return mergeFrom(
            (io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest other) {
      if (other == io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest
          .getDefaultInstance())
        return this;
      if (!other.getTenant().isEmpty()) {
        tenant_ = other.tenant_;
        onChanged();
      }
      if (!other.getRowsJson().isEmpty()) {
        rowsJson_ = other.rowsJson_;
        onChanged();
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest) e
            .getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object tenant_ = "";

    /**
     * <code>string tenant = 1;</code>
     */
    public String getTenant() {
      Object ref = tenant_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tenant_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string tenant = 1;</code>
     */
    public com.google.protobuf.ByteString getTenantBytes() {
      Object ref = tenant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tenant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string tenant = 1;</code>
     */
    public Builder setTenant(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      tenant_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string tenant = 1;</code>
     */
    public Builder clearTenant() {

      tenant_ = getDefaultInstance().getTenant();
      onChanged();
      return this;
    }

    /**
     * <code>string tenant = 1;</code>
     */
    public Builder setTenantBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      tenant_ = value;
      onChanged();
      return this;
    }

    private Object rowsJson_ = "";

    /**
     * <code>string rowsJson = 2;</code>
     */
    public String getRowsJson() {
      Object ref = rowsJson_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rowsJson_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string rowsJson = 2;</code>
     */
    public com.google.protobuf.ByteString getRowsJsonBytes() {
      Object ref = rowsJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rowsJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string rowsJson = 2;</code>
     */
    public Builder setRowsJson(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      rowsJson_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string rowsJson = 2;</code>
     */
    public Builder clearRowsJson() {

      rowsJson_ = getDefaultInstance().getRowsJson();
      onChanged();
      return this;
    }

    /**
     * <code>string rowsJson = 2;</code>
     */
    public Builder setRowsJsonBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      rowsJson_ = value;
      onChanged();
      return this;
    }

    private Object traceId_ = "";

    /**
     * <code>string traceId = 3;</code>
     */
    public String getTraceId() {
      Object ref = traceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string traceId = 3;</code>
     */
    public com.google.protobuf.ByteString getTraceIdBytes() {
      Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string traceId = 3;</code>
     */
    public Builder setTraceId(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      traceId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string traceId = 3;</code>
     */
    public Builder clearTraceId() {

      traceId_ = getDefaultInstance().getTraceId();
      onChanged();
      return this;
    }

    /**
     * <code>string traceId = 3;</code>
     */
    public Builder setTraceIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      traceId_ = value;
      onChanged();
      return this;
    }

    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QueryAlarmHistoryPageRequest)
  }

  // @@protoc_insertion_point(class_scope:QueryAlarmHistoryPageRequest)
  private static final io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest();
  }

  public static io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryAlarmHistoryPageRequest> PARSER =
      new com.google.protobuf.AbstractParser<QueryAlarmHistoryPageRequest>() {
        public QueryAlarmHistoryPageRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryAlarmHistoryPageRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<QueryAlarmHistoryPageRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QueryAlarmHistoryPageRequest> getParserForType() {
    return PARSER;
  }

  public io.holoinsight.server.home.proto.alarm.QueryAlarmHistoryPageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

