/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: TableService.proto

package io.holoinsight.server.meta.proto.table;

public interface TableBaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scheduler.TableBaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string errMsg = 2;</code>
   */
  java.lang.String getErrMsg();

  /**
   * <code>string errMsg = 2;</code>
   */
  com.google.protobuf.ByteString getErrMsgBytes();
}
