/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: gateway-for-agent.proto

package io.holoinsight.server.gateway.grpc;

public interface WriteMetricsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.gateway.grpc.WriteMetricsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.holoinsight.server.gateway.grpc.common.CommonResponseHeader header = 1;</code>
   * 
   * @return Whether the header field is set.
   */
  boolean hasHeader();

  /**
   * <code>.io.holoinsight.server.gateway.grpc.common.CommonResponseHeader header = 1;</code>
   * 
   * @return The header.
   */
  io.holoinsight.server.gateway.grpc.common.CommonResponseHeader getHeader();

  /**
   * <code>.io.holoinsight.server.gateway.grpc.common.CommonResponseHeader header = 1;</code>
   */
  io.holoinsight.server.gateway.grpc.common.CommonResponseHeaderOrBuilder getHeaderOrBuilder();
}
