/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

package io.holoinsight.server.gateway.grpc.common;

public interface CommonRequestHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.gateway.grpc.common.CommonRequestHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apikey = 1;</code>
   * 
   * @return The apikey.
   */
  java.lang.String getApikey();

  /**
   * <code>string apikey = 1;</code>
   * 
   * @return The bytes for apikey.
   */
  com.google.protobuf.ByteString getApikeyBytes();

  /**
   * <code>string trace_id = 2;</code>
   * 
   * @return The traceId.
   */
  java.lang.String getTraceId();

  /**
   * <code>string trace_id = 2;</code>
   * 
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString getTraceIdBytes();

  /**
   * <code>map&lt;string, string&gt; extension = 3;</code>
   */
  int getExtensionCount();

  /**
   * <code>map&lt;string, string&gt; extension = 3;</code>
   */
  boolean containsExtension(java.lang.String key);

  /**
   * Use {@link #getExtensionMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String> getExtension();

  /**
   * <code>map&lt;string, string&gt; extension = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String> getExtensionMap();

  /**
   * <code>map&lt;string, string&gt; extension = 3;</code>
   */

  java.lang.String getExtensionOrDefault(java.lang.String key, java.lang.String defaultValue);

  /**
   * <code>map&lt;string, string&gt; extension = 3;</code>
   */

  java.lang.String getExtensionOrThrow(java.lang.String key);
}
