---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clusteragent
  namespace: holoinsight-example
  labels:
    app: clusteragent
spec:
  serviceName: clusteragent
  replicas: 1
  selector:
    matchLabels:
      app: clusteragent
  template:
    metadata:
      labels:
        app: clusteragent
        hi_common_version: '2'
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      initContainers:
      # Wait for holoinsight-server to be ready and then start the clusteragent.
      # Otherwise, the first meta full sync request will fail because clusteragent starts faster than the server side.
      # And it needs to wait another 5min to trigger next meta full sync request.
      - name: wait-for-server
        image: tehkapa/docker-wait-for-dependencies
        args:
        - registry:7202
      containers:
      - name: clusteragent
        image: holoinsight/agent:latest
        imagePullPolicy: Always
        env:
        - name: HI_APP
          value: clusteragent
        - name: HI_AGENT_MODE
          value: "clusteragent"
        - name: HOSTFS
          value: "/hostfs"
        - name: HI_APIKEY
          valueFrom:
            configMapKeyRef:
              key: apikey
              name: holoinsight-agent-cm
        - name: HI_REGISTRY_ADDR
          valueFrom:
            configMapKeyRef:
              key: serverRegistryAddr
              name: holoinsight-agent-cm
        - name: HI_GATEWAY_ADDR
          valueFrom:
            configMapKeyRef:
              key: serverGatewayAddr
              name: holoinsight-agent-cm
        - name: HI_REGISTRY_SECURE
          valueFrom:
            configMapKeyRef:
              key: serverGrpcSecure
              name: holoinsight-agent-cm
        - name: HI_GATEWAY_SECURE
          valueFrom:
            configMapKeyRef:
              key: serverGrpcSecure
              name: holoinsight-agent-cm
        - name: HI_WORKSPACE
          valueFrom:
            configMapKeyRef:
              key: workspace
              name: holoinsight-agent-cm
        - name: HI_CLUSTER
          valueFrom:
            configMapKeyRef:
              key: cluster
              name: holoinsight-agent-cm
        - name: USESUPERVISOR
          value: "false"

        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_RESOURCES_LIMIT_CPU
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: K8S_RESOURCES_LIMIT_MEMORY
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "0.25"
            memory: "256Mi"
