# kubectl -n holoinsight-example exec -it mongodb-0 -- mongosh holoinsight

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: holoinsight-example
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      restartPolicy: Always
      volumes:
      - name: cm
        configMap:
          name: mongo-cm
      containers:
      - name: mongo
        # mongo with version >= v5 requires CPU AVX. So we use 4.4.18 is enough
        # https://stackoverflow.com/questions/70818543/mongo-db-deployment-not-working-in-kubernetes-because-processor-doesnt-have-avx
        image: mongo:4.4.18
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        - name: MONGO_INITDB_DATABASE
          value: holoinsight
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 3
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.js
          name: cm
          subPath: init.js

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-cm
  namespace: holoinsight-example
data:
  init.js: |
    db.createUser({
        user: "holoinsight",
        pwd: "holoinsight",
        roles: [
            {role: "readWrite", db: "holoinsight"}
        ]
    })

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: holoinsight-example
  labels:
    name: mongo
spec:
  clusterIP: None
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
