/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-prod.proto

package io.holoinsight.server.registry.grpc.prod;

/**
 * Protobuf type {@code io.holoinsight.server.registry.grpc.prod.PreviewFileRequest}
 */
public final class PreviewFileRequest extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.holoinsight.server.registry.grpc.prod.PreviewFileRequest)
    PreviewFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use PreviewFileRequest.newBuilder() to construct.
  private PreviewFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private PreviewFileRequest() {
    agentId_ = "";
    path_ = "";
    charset_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new PreviewFileRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private PreviewFileRequest(com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.holoinsight.server.common.grpc.CommonRequestHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(
                io.holoinsight.server.common.grpc.CommonRequestHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            agentId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            charset_ = s;
            break;
          }
          case 40: {

            maxLines_ = input.readInt32();
            break;
          }
          case 48: {

            maxBytes_ = input.readInt32();
            break;
          }
          case 58: {
            io.holoinsight.server.registry.grpc.prod.TargetIdentifier.Builder subBuilder = null;
            if (target_ != null) {
              subBuilder = target_.toBuilder();
            }
            target_ = input.readMessage(
                io.holoinsight.server.registry.grpc.prod.TargetIdentifier.parser(),
                extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(target_);
              target_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.holoinsight.server.registry.grpc.prod.RegistryForProdProtos.internal_static_io_holoinsight_server_registry_grpc_prod_PreviewFileRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
    return io.holoinsight.server.registry.grpc.prod.RegistryForProdProtos.internal_static_io_holoinsight_server_registry_grpc_prod_PreviewFileRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.class,
            io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private io.holoinsight.server.common.grpc.CommonRequestHeader header_;

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
   */
  public io.holoinsight.server.common.grpc.CommonRequestHeader getHeader() {
    return header_ == null
        ? io.holoinsight.server.common.grpc.CommonRequestHeader.getDefaultInstance()
        : header_;
  }

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
   */
  public io.holoinsight.server.common.grpc.CommonRequestHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int AGENT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object agentId_;

  /**
   * <code>string agent_id = 2;</code>
   */
  public java.lang.String getAgentId() {
    java.lang.Object ref = agentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentId_ = s;
      return s;
    }
  }

  /**
   * <code>string agent_id = 2;</code>
   */
  public com.google.protobuf.ByteString getAgentIdBytes() {
    java.lang.Object ref = agentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      agentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 3;
  private volatile java.lang.Object path_;

  /**
   * <pre>
   * 日志路径
   * </pre>
   *
   * <code>string path = 3;</code>
   */
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * 日志路径
   * </pre>
   *
   * <code>string path = 3;</code>
   */
  public com.google.protobuf.ByteString getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHARSET_FIELD_NUMBER = 4;
  private volatile java.lang.Object charset_;

  /**
   * <pre>
   * 如果没有提供编码则agent会猜测编码
   * </pre>
   *
   * <code>string charset = 4;</code>
   */
  public java.lang.String getCharset() {
    java.lang.Object ref = charset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      charset_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * 如果没有提供编码则agent会猜测编码
   * </pre>
   *
   * <code>string charset = 4;</code>
   */
  public com.google.protobuf.ByteString getCharsetBytes() {
    java.lang.Object ref = charset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      charset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAXLINES_FIELD_NUMBER = 5;
  private int maxLines_;

  /**
   * <pre>
   * 最多的行数
   * </pre>
   *
   * <code>int32 maxLines = 5;</code>
   */
  public int getMaxLines() {
    return maxLines_;
  }

  public static final int MAXBYTES_FIELD_NUMBER = 6;
  private int maxBytes_;

  /**
   * <pre>
   * 最多的字节数
   * </pre>
   *
   * <code>int32 maxBytes = 6;</code>
   */
  public int getMaxBytes() {
    return maxBytes_;
  }

  public static final int TARGET_FIELD_NUMBER = 7;
  private io.holoinsight.server.registry.grpc.prod.TargetIdentifier target_;

  /**
   * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
   */
  public boolean hasTarget() {
    return target_ != null;
  }

  /**
   * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
   */
  public io.holoinsight.server.registry.grpc.prod.TargetIdentifier getTarget() {
    return target_ == null
        ? io.holoinsight.server.registry.grpc.prod.TargetIdentifier.getDefaultInstance()
        : target_;
  }

  /**
   * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
   */
  public io.holoinsight.server.registry.grpc.prod.TargetIdentifierOrBuilder getTargetOrBuilder() {
    return getTarget();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!getAgentIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, agentId_);
    }
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, path_);
    }
    if (!getCharsetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, charset_);
    }
    if (maxLines_ != 0) {
      output.writeInt32(5, maxLines_);
    }
    if (maxBytes_ != 0) {
      output.writeInt32(6, maxBytes_);
    }
    if (target_ != null) {
      output.writeMessage(7, getTarget());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getHeader());
    }
    if (!getAgentIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, agentId_);
    }
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, path_);
    }
    if (!getCharsetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, charset_);
    }
    if (maxLines_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, maxLines_);
    }
    if (maxBytes_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(6, maxBytes_);
    }
    if (target_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, getTarget());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.holoinsight.server.registry.grpc.prod.PreviewFileRequest)) {
      return super.equals(obj);
    }
    io.holoinsight.server.registry.grpc.prod.PreviewFileRequest other =
        (io.holoinsight.server.registry.grpc.prod.PreviewFileRequest) obj;

    if (hasHeader() != other.hasHeader())
      return false;
    if (hasHeader()) {
      if (!getHeader().equals(other.getHeader()))
        return false;
    }
    if (!getAgentId().equals(other.getAgentId()))
      return false;
    if (!getPath().equals(other.getPath()))
      return false;
    if (!getCharset().equals(other.getCharset()))
      return false;
    if (getMaxLines() != other.getMaxLines())
      return false;
    if (getMaxBytes() != other.getMaxBytes())
      return false;
    if (hasTarget() != other.hasTarget())
      return false;
    if (hasTarget()) {
      if (!getTarget().equals(other.getTarget()))
        return false;
    }
    if (!unknownFields.equals(other.unknownFields))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAgentId().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + CHARSET_FIELD_NUMBER;
    hash = (53 * hash) + getCharset().hashCode();
    hash = (37 * hash) + MAXLINES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxLines();
    hash = (37 * hash) + MAXBYTES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxBytes();
    if (hasTarget()) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.holoinsight.server.registry.grpc.prod.PreviewFileRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code io.holoinsight.server.registry.grpc.prod.PreviewFileRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:io.holoinsight.server.registry.grpc.prod.PreviewFileRequest)
      io.holoinsight.server.registry.grpc.prod.PreviewFileRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.holoinsight.server.registry.grpc.prod.RegistryForProdProtos.internal_static_io_holoinsight_server_registry_grpc_prod_PreviewFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return io.holoinsight.server.registry.grpc.prod.RegistryForProdProtos.internal_static_io_holoinsight_server_registry_grpc_prod_PreviewFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.class,
              io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.Builder.class);
    }

    // Construct using io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {}

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      agentId_ = "";

      path_ = "";

      charset_ = "";

      maxLines_ = 0;

      maxBytes_ = 0;

      if (targetBuilder_ == null) {
        target_ = null;
      } else {
        target_ = null;
        targetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.holoinsight.server.registry.grpc.prod.RegistryForProdProtos.internal_static_io_holoinsight_server_registry_grpc_prod_PreviewFileRequest_descriptor;
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.prod.PreviewFileRequest getDefaultInstanceForType() {
      return io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.prod.PreviewFileRequest build() {
      io.holoinsight.server.registry.grpc.prod.PreviewFileRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.prod.PreviewFileRequest buildPartial() {
      io.holoinsight.server.registry.grpc.prod.PreviewFileRequest result =
          new io.holoinsight.server.registry.grpc.prod.PreviewFileRequest(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.agentId_ = agentId_;
      result.path_ = path_;
      result.charset_ = charset_;
      result.maxLines_ = maxLines_;
      result.maxBytes_ = maxBytes_;
      if (targetBuilder_ == null) {
        result.target_ = target_;
      } else {
        result.target_ = targetBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.holoinsight.server.registry.grpc.prod.PreviewFileRequest) {
        return mergeFrom((io.holoinsight.server.registry.grpc.prod.PreviewFileRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.holoinsight.server.registry.grpc.prod.PreviewFileRequest other) {
      if (other == io.holoinsight.server.registry.grpc.prod.PreviewFileRequest.getDefaultInstance())
        return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getAgentId().isEmpty()) {
        agentId_ = other.agentId_;
        onChanged();
      }
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (!other.getCharset().isEmpty()) {
        charset_ = other.charset_;
        onChanged();
      }
      if (other.getMaxLines() != 0) {
        setMaxLines(other.getMaxLines());
      }
      if (other.getMaxBytes() != 0) {
        setMaxBytes(other.getMaxBytes());
      }
      if (other.hasTarget()) {
        mergeTarget(other.getTarget());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      io.holoinsight.server.registry.grpc.prod.PreviewFileRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (io.holoinsight.server.registry.grpc.prod.PreviewFileRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.holoinsight.server.common.grpc.CommonRequestHeader header_;
    private com.google.protobuf.SingleFieldBuilderV3<io.holoinsight.server.common.grpc.CommonRequestHeader, io.holoinsight.server.common.grpc.CommonRequestHeader.Builder, io.holoinsight.server.common.grpc.CommonRequestHeaderOrBuilder> headerBuilder_;

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public io.holoinsight.server.common.grpc.CommonRequestHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null
            ? io.holoinsight.server.common.grpc.CommonRequestHeader.getDefaultInstance()
            : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public Builder setHeader(io.holoinsight.server.common.grpc.CommonRequestHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public Builder setHeader(
        io.holoinsight.server.common.grpc.CommonRequestHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public Builder mergeHeader(io.holoinsight.server.common.grpc.CommonRequestHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ = io.holoinsight.server.common.grpc.CommonRequestHeader.newBuilder(header_)
              .mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public io.holoinsight.server.common.grpc.CommonRequestHeader.Builder getHeaderBuilder() {

      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    public io.holoinsight.server.common.grpc.CommonRequestHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null
            ? io.holoinsight.server.common.grpc.CommonRequestHeader.getDefaultInstance()
            : header_;
      }
    }

    /**
     * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<io.holoinsight.server.common.grpc.CommonRequestHeader, io.holoinsight.server.common.grpc.CommonRequestHeader.Builder, io.holoinsight.server.common.grpc.CommonRequestHeaderOrBuilder> getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<io.holoinsight.server.common.grpc.CommonRequestHeader, io.holoinsight.server.common.grpc.CommonRequestHeader.Builder, io.holoinsight.server.common.grpc.CommonRequestHeaderOrBuilder>(
                getHeader(), getParentForChildren(), isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object agentId_ = "";

    /**
     * <code>string agent_id = 2;</code>
     */
    public java.lang.String getAgentId() {
      java.lang.Object ref = agentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string agent_id = 2;</code>
     */
    public com.google.protobuf.ByteString getAgentIdBytes() {
      java.lang.Object ref = agentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        agentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string agent_id = 2;</code>
     */
    public Builder setAgentId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      agentId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string agent_id = 2;</code>
     */
    public Builder clearAgentId() {

      agentId_ = getDefaultInstance().getAgentId();
      onChanged();
      return this;
    }

    /**
     * <code>string agent_id = 2;</code>
     */
    public Builder setAgentIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      agentId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object path_ = "";

    /**
     * <pre>
     * 日志路径
     * </pre>
     *
     * <code>string path = 3;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     * 日志路径
     * </pre>
     *
     * <code>string path = 3;</code>
     */
    public com.google.protobuf.ByteString getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * 日志路径
     * </pre>
     *
     * <code>string path = 3;</code>
     */
    public Builder setPath(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      path_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 日志路径
     * </pre>
     *
     * <code>string path = 3;</code>
     */
    public Builder clearPath() {

      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 日志路径
     * </pre>
     *
     * <code>string path = 3;</code>
     */
    public Builder setPathBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      path_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object charset_ = "";

    /**
     * <pre>
     * 如果没有提供编码则agent会猜测编码
     * </pre>
     *
     * <code>string charset = 4;</code>
     */
    public java.lang.String getCharset() {
      java.lang.Object ref = charset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        charset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     * 如果没有提供编码则agent会猜测编码
     * </pre>
     *
     * <code>string charset = 4;</code>
     */
    public com.google.protobuf.ByteString getCharsetBytes() {
      java.lang.Object ref = charset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        charset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * 如果没有提供编码则agent会猜测编码
     * </pre>
     *
     * <code>string charset = 4;</code>
     */
    public Builder setCharset(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      charset_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 如果没有提供编码则agent会猜测编码
     * </pre>
     *
     * <code>string charset = 4;</code>
     */
    public Builder clearCharset() {

      charset_ = getDefaultInstance().getCharset();
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 如果没有提供编码则agent会猜测编码
     * </pre>
     *
     * <code>string charset = 4;</code>
     */
    public Builder setCharsetBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      charset_ = value;
      onChanged();
      return this;
    }

    private int maxLines_;

    /**
     * <pre>
     * 最多的行数
     * </pre>
     *
     * <code>int32 maxLines = 5;</code>
     */
    public int getMaxLines() {
      return maxLines_;
    }

    /**
     * <pre>
     * 最多的行数
     * </pre>
     *
     * <code>int32 maxLines = 5;</code>
     */
    public Builder setMaxLines(int value) {

      maxLines_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 最多的行数
     * </pre>
     *
     * <code>int32 maxLines = 5;</code>
     */
    public Builder clearMaxLines() {

      maxLines_ = 0;
      onChanged();
      return this;
    }

    private int maxBytes_;

    /**
     * <pre>
     * 最多的字节数
     * </pre>
     *
     * <code>int32 maxBytes = 6;</code>
     */
    public int getMaxBytes() {
      return maxBytes_;
    }

    /**
     * <pre>
     * 最多的字节数
     * </pre>
     *
     * <code>int32 maxBytes = 6;</code>
     */
    public Builder setMaxBytes(int value) {

      maxBytes_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 最多的字节数
     * </pre>
     *
     * <code>int32 maxBytes = 6;</code>
     */
    public Builder clearMaxBytes() {

      maxBytes_ = 0;
      onChanged();
      return this;
    }

    private io.holoinsight.server.registry.grpc.prod.TargetIdentifier target_;
    private com.google.protobuf.SingleFieldBuilderV3<io.holoinsight.server.registry.grpc.prod.TargetIdentifier, io.holoinsight.server.registry.grpc.prod.TargetIdentifier.Builder, io.holoinsight.server.registry.grpc.prod.TargetIdentifierOrBuilder> targetBuilder_;

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public boolean hasTarget() {
      return targetBuilder_ != null || target_ != null;
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public io.holoinsight.server.registry.grpc.prod.TargetIdentifier getTarget() {
      if (targetBuilder_ == null) {
        return target_ == null
            ? io.holoinsight.server.registry.grpc.prod.TargetIdentifier.getDefaultInstance()
            : target_;
      } else {
        return targetBuilder_.getMessage();
      }
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public Builder setTarget(io.holoinsight.server.registry.grpc.prod.TargetIdentifier value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        target_ = value;
        onChanged();
      } else {
        targetBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public Builder setTarget(
        io.holoinsight.server.registry.grpc.prod.TargetIdentifier.Builder builderForValue) {
      if (targetBuilder_ == null) {
        target_ = builderForValue.build();
        onChanged();
      } else {
        targetBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public Builder mergeTarget(io.holoinsight.server.registry.grpc.prod.TargetIdentifier value) {
      if (targetBuilder_ == null) {
        if (target_ != null) {
          target_ = io.holoinsight.server.registry.grpc.prod.TargetIdentifier.newBuilder(target_)
              .mergeFrom(value).buildPartial();
        } else {
          target_ = value;
        }
        onChanged();
      } else {
        targetBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public Builder clearTarget() {
      if (targetBuilder_ == null) {
        target_ = null;
        onChanged();
      } else {
        target_ = null;
        targetBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public io.holoinsight.server.registry.grpc.prod.TargetIdentifier.Builder getTargetBuilder() {

      onChanged();
      return getTargetFieldBuilder().getBuilder();
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    public io.holoinsight.server.registry.grpc.prod.TargetIdentifierOrBuilder getTargetOrBuilder() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilder();
      } else {
        return target_ == null
            ? io.holoinsight.server.registry.grpc.prod.TargetIdentifier.getDefaultInstance()
            : target_;
      }
    }

    /**
     * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<io.holoinsight.server.registry.grpc.prod.TargetIdentifier, io.holoinsight.server.registry.grpc.prod.TargetIdentifier.Builder, io.holoinsight.server.registry.grpc.prod.TargetIdentifierOrBuilder> getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<io.holoinsight.server.registry.grpc.prod.TargetIdentifier, io.holoinsight.server.registry.grpc.prod.TargetIdentifier.Builder, io.holoinsight.server.registry.grpc.prod.TargetIdentifierOrBuilder>(
                getTarget(), getParentForChildren(), isClean());
        target_ = null;
      }
      return targetBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.holoinsight.server.registry.grpc.prod.PreviewFileRequest)
  }

  // @@protoc_insertion_point(class_scope:io.holoinsight.server.registry.grpc.prod.PreviewFileRequest)
  private static final io.holoinsight.server.registry.grpc.prod.PreviewFileRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.holoinsight.server.registry.grpc.prod.PreviewFileRequest();
  }

  public static io.holoinsight.server.registry.grpc.prod.PreviewFileRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreviewFileRequest> PARSER =
      new com.google.protobuf.AbstractParser<PreviewFileRequest>() {
        @java.lang.Override
        public PreviewFileRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PreviewFileRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<PreviewFileRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreviewFileRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.holoinsight.server.registry.grpc.prod.PreviewFileRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
