/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-prod.proto

package io.holoinsight.server.registry.grpc.prod;

public interface SplitLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.registry.grpc.prod.SplitLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
   */
  boolean hasHeader();

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
   */
  io.holoinsight.server.common.grpc.CommonRequestHeader getHeader();

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonRequestHeader header = 1;</code>
   */
  io.holoinsight.server.common.grpc.CommonRequestHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>string agent_id = 2;</code>
   */
  java.lang.String getAgentId();

  /**
   * <code>string agent_id = 2;</code>
   */
  com.google.protobuf.ByteString getAgentIdBytes();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();

  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString getContentBytes();

  /**
   * <code>string regexp = 4;</code>
   */
  java.lang.String getRegexp();

  /**
   * <code>string regexp = 4;</code>
   */
  com.google.protobuf.ByteString getRegexpBytes();

  /**
   * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 5;</code>
   */
  boolean hasTarget();

  /**
   * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 5;</code>
   */
  io.holoinsight.server.registry.grpc.prod.TargetIdentifier getTarget();

  /**
   * <code>.io.holoinsight.server.registry.grpc.prod.TargetIdentifier target = 5;</code>
   */
  io.holoinsight.server.registry.grpc.prod.TargetIdentifierOrBuilder getTargetOrBuilder();
}
