/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-prod.proto

package io.holoinsight.server.registry.grpc.prod;

public interface SplitLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.registry.grpc.prod.SplitLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonResponseHeader header = 1;</code>
   */
  boolean hasHeader();

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonResponseHeader header = 1;</code>
   */
  io.holoinsight.server.common.grpc.CommonResponseHeader getHeader();

  /**
   * <code>.io.holoinsight.server.common.grpc.CommonResponseHeader header = 1;</code>
   */
  io.holoinsight.server.common.grpc.CommonResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>map&lt;string, string&gt; result = 2;</code>
   */
  int getResultCount();

  /**
   * <code>map&lt;string, string&gt; result = 2;</code>
   */
  boolean containsResult(java.lang.String key);

  /**
   * Use {@link #getResultMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String> getResult();

  /**
   * <code>map&lt;string, string&gt; result = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String> getResultMap();

  /**
   * <code>map&lt;string, string&gt; result = 2;</code>
   */

  java.lang.String getResultOrDefault(java.lang.String key, java.lang.String defaultValue);

  /**
   * <code>map&lt;string, string&gt; result = 2;</code>
   */

  java.lang.String getResultOrThrow(java.lang.String key);
}
