/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-agent.proto

package io.holoinsight.server.registry.grpc.agent;

/**
 * Protobuf type {@code io.holoinsight.server.registry.grpc.agent.AgentK8sInfo}
 */
public final class AgentK8sInfo extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.holoinsight.server.registry.grpc.agent.AgentK8sInfo)
    AgentK8sInfoOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use AgentK8sInfo.newBuilder() to construct.
  private AgentK8sInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private AgentK8sInfo() {
    hostIp_ = "";
    namespace_ = "";
    pod_ = "";
    nodeHostname_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new AgentK8sInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private AgentK8sInfo(com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hostIp_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            namespace_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pod_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeHostname_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_AgentK8sInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
    return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_AgentK8sInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.class,
            io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.Builder.class);
  }

  public static final int HOST_IP_FIELD_NUMBER = 1;
  private volatile java.lang.Object hostIp_;

  /**
   * <code>string host_ip = 1;</code>
   */
  public java.lang.String getHostIp() {
    java.lang.Object ref = hostIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostIp_ = s;
      return s;
    }
  }

  /**
   * <code>string host_ip = 1;</code>
   */
  public com.google.protobuf.ByteString getHostIpBytes() {
    java.lang.Object ref = hostIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      hostIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMESPACE_FIELD_NUMBER = 2;
  private volatile java.lang.Object namespace_;

  /**
   * <code>string namespace = 2;</code>
   */
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }

  /**
   * <code>string namespace = 2;</code>
   */
  public com.google.protobuf.ByteString getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POD_FIELD_NUMBER = 3;
  private volatile java.lang.Object pod_;

  /**
   * <code>string pod = 3;</code>
   */
  public java.lang.String getPod() {
    java.lang.Object ref = pod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pod_ = s;
      return s;
    }
  }

  /**
   * <code>string pod = 3;</code>
   */
  public com.google.protobuf.ByteString getPodBytes() {
    java.lang.Object ref = pod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      pod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_HOSTNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object nodeHostname_;

  /**
   * <code>string node_hostname = 4;</code>
   */
  public java.lang.String getNodeHostname() {
    java.lang.Object ref = nodeHostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeHostname_ = s;
      return s;
    }
  }

  /**
   * <code>string node_hostname = 4;</code>
   */
  public com.google.protobuf.ByteString getNodeHostnameBytes() {
    java.lang.Object ref = nodeHostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      nodeHostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getHostIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostIp_);
    }
    if (!getNamespaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, namespace_);
    }
    if (!getPodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pod_);
    }
    if (!getNodeHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nodeHostname_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (!getHostIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostIp_);
    }
    if (!getNamespaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, namespace_);
    }
    if (!getPodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pod_);
    }
    if (!getNodeHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nodeHostname_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.holoinsight.server.registry.grpc.agent.AgentK8sInfo)) {
      return super.equals(obj);
    }
    io.holoinsight.server.registry.grpc.agent.AgentK8sInfo other =
        (io.holoinsight.server.registry.grpc.agent.AgentK8sInfo) obj;

    if (!getHostIp().equals(other.getHostIp()))
      return false;
    if (!getNamespace().equals(other.getNamespace()))
      return false;
    if (!getPod().equals(other.getPod()))
      return false;
    if (!getNodeHostname().equals(other.getNodeHostname()))
      return false;
    if (!unknownFields.equals(other.unknownFields))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOST_IP_FIELD_NUMBER;
    hash = (53 * hash) + getHostIp().hashCode();
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    hash = (37 * hash) + POD_FIELD_NUMBER;
    hash = (53 * hash) + getPod().hashCode();
    hash = (37 * hash) + NODE_HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNodeHostname().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.holoinsight.server.registry.grpc.agent.AgentK8sInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code io.holoinsight.server.registry.grpc.agent.AgentK8sInfo}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:io.holoinsight.server.registry.grpc.agent.AgentK8sInfo)
      io.holoinsight.server.registry.grpc.agent.AgentK8sInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_AgentK8sInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_AgentK8sInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.class,
              io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.Builder.class);
    }

    // Construct using io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {}

    @java.lang.Override
    public Builder clear() {
      super.clear();
      hostIp_ = "";

      namespace_ = "";

      pod_ = "";

      nodeHostname_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_AgentK8sInfo_descriptor;
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.agent.AgentK8sInfo getDefaultInstanceForType() {
      return io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.getDefaultInstance();
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.agent.AgentK8sInfo build() {
      io.holoinsight.server.registry.grpc.agent.AgentK8sInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.agent.AgentK8sInfo buildPartial() {
      io.holoinsight.server.registry.grpc.agent.AgentK8sInfo result =
          new io.holoinsight.server.registry.grpc.agent.AgentK8sInfo(this);
      result.hostIp_ = hostIp_;
      result.namespace_ = namespace_;
      result.pod_ = pod_;
      result.nodeHostname_ = nodeHostname_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.holoinsight.server.registry.grpc.agent.AgentK8sInfo) {
        return mergeFrom((io.holoinsight.server.registry.grpc.agent.AgentK8sInfo) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.holoinsight.server.registry.grpc.agent.AgentK8sInfo other) {
      if (other == io.holoinsight.server.registry.grpc.agent.AgentK8sInfo.getDefaultInstance())
        return this;
      if (!other.getHostIp().isEmpty()) {
        hostIp_ = other.hostIp_;
        onChanged();
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        onChanged();
      }
      if (!other.getPod().isEmpty()) {
        pod_ = other.pod_;
        onChanged();
      }
      if (!other.getNodeHostname().isEmpty()) {
        nodeHostname_ = other.nodeHostname_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      io.holoinsight.server.registry.grpc.agent.AgentK8sInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (io.holoinsight.server.registry.grpc.agent.AgentK8sInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hostIp_ = "";

    /**
     * <code>string host_ip = 1;</code>
     */
    public java.lang.String getHostIp() {
      java.lang.Object ref = hostIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string host_ip = 1;</code>
     */
    public com.google.protobuf.ByteString getHostIpBytes() {
      java.lang.Object ref = hostIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        hostIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string host_ip = 1;</code>
     */
    public Builder setHostIp(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      hostIp_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string host_ip = 1;</code>
     */
    public Builder clearHostIp() {

      hostIp_ = getDefaultInstance().getHostIp();
      onChanged();
      return this;
    }

    /**
     * <code>string host_ip = 1;</code>
     */
    public Builder setHostIpBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      hostIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object namespace_ = "";

    /**
     * <code>string namespace = 2;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string namespace = 2;</code>
     */
    public com.google.protobuf.ByteString getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string namespace = 2;</code>
     */
    public Builder setNamespace(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      namespace_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string namespace = 2;</code>
     */
    public Builder clearNamespace() {

      namespace_ = getDefaultInstance().getNamespace();
      onChanged();
      return this;
    }

    /**
     * <code>string namespace = 2;</code>
     */
    public Builder setNamespaceBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      namespace_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pod_ = "";

    /**
     * <code>string pod = 3;</code>
     */
    public java.lang.String getPod() {
      java.lang.Object ref = pod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string pod = 3;</code>
     */
    public com.google.protobuf.ByteString getPodBytes() {
      java.lang.Object ref = pod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        pod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string pod = 3;</code>
     */
    public Builder setPod(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      pod_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string pod = 3;</code>
     */
    public Builder clearPod() {

      pod_ = getDefaultInstance().getPod();
      onChanged();
      return this;
    }

    /**
     * <code>string pod = 3;</code>
     */
    public Builder setPodBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      pod_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nodeHostname_ = "";

    /**
     * <code>string node_hostname = 4;</code>
     */
    public java.lang.String getNodeHostname() {
      java.lang.Object ref = nodeHostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeHostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string node_hostname = 4;</code>
     */
    public com.google.protobuf.ByteString getNodeHostnameBytes() {
      java.lang.Object ref = nodeHostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        nodeHostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string node_hostname = 4;</code>
     */
    public Builder setNodeHostname(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      nodeHostname_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string node_hostname = 4;</code>
     */
    public Builder clearNodeHostname() {

      nodeHostname_ = getDefaultInstance().getNodeHostname();
      onChanged();
      return this;
    }

    /**
     * <code>string node_hostname = 4;</code>
     */
    public Builder setNodeHostnameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      nodeHostname_ = value;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.holoinsight.server.registry.grpc.agent.AgentK8sInfo)
  }

  // @@protoc_insertion_point(class_scope:io.holoinsight.server.registry.grpc.agent.AgentK8sInfo)
  private static final io.holoinsight.server.registry.grpc.agent.AgentK8sInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.holoinsight.server.registry.grpc.agent.AgentK8sInfo();
  }

  public static io.holoinsight.server.registry.grpc.agent.AgentK8sInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentK8sInfo> PARSER =
      new com.google.protobuf.AbstractParser<AgentK8sInfo>() {
        @java.lang.Override
        public AgentK8sInfo parsePartialFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AgentK8sInfo(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<AgentK8sInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentK8sInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.holoinsight.server.registry.grpc.agent.AgentK8sInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
