/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-agent.proto

package io.holoinsight.server.registry.grpc.agent;

public interface BiStreamClientHandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.registry.grpc.agent.BiStreamClientHandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string agent_id = 1;</code>
   */
  java.lang.String getAgentId();

  /**
   * <code>string agent_id = 1;</code>
   */
  com.google.protobuf.ByteString getAgentIdBytes();

  /**
   * <code>int64 version = 2;</code>
   */
  long getVersion();
}
