/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-agent.proto

package io.holoinsight.server.registry.grpc.agent;

public interface CollectConfigsBucketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 该bucket的状态
   * </pre>
   *
   * <code>string state = 1;</code>
   */
  java.lang.String getState();

  /**
   * <pre>
   * 该bucket的状态
   * </pre>
   *
   * <code>string state = 1;</code>
   */
  com.google.protobuf.ByteString getStateBytes();

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  java.util.List<io.holoinsight.server.registry.grpc.agent.CollectTask> getCollectTasksList();

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  io.holoinsight.server.registry.grpc.agent.CollectTask getCollectTasks(int index);

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  int getCollectTasksCount();

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  java.util.List<? extends io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder> getCollectTasksOrBuilderList();

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder getCollectTasksOrBuilder(
      int index);
}
