/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: registry-for-agent.proto

package io.holoinsight.server.registry.grpc.agent;

/**
 * Protobuf type {@code io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket}
 */
public final class CollectConfigsBucket extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket)
    CollectConfigsBucketOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use CollectConfigsBucket.newBuilder() to construct.
  private CollectConfigsBucket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CollectConfigsBucket() {
    state_ = "";
    collectTasks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new CollectConfigsBucket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private CollectConfigsBucket(com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            state_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              collectTasks_ =
                  new java.util.ArrayList<io.holoinsight.server.registry.grpc.agent.CollectTask>();
              mutable_bitField0_ |= 0x00000001;
            }
            collectTasks_.add(input.readMessage(
                io.holoinsight.server.registry.grpc.agent.CollectTask.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        collectTasks_ = java.util.Collections.unmodifiableList(collectTasks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_CollectConfigsBucket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
    return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_CollectConfigsBucket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket.class,
            io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket.Builder.class);
  }

  public static final int STATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object state_;

  /**
   * <pre>
   * 该bucket的状态
   * </pre>
   *
   * <code>string state = 1;</code>
   */
  public java.lang.String getState() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      state_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * 该bucket的状态
   * </pre>
   *
   * <code>string state = 1;</code>
   */
  public com.google.protobuf.ByteString getStateBytes() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      state_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECT_TASKS_FIELD_NUMBER = 2;
  private java.util.List<io.holoinsight.server.registry.grpc.agent.CollectTask> collectTasks_;

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  public java.util.List<io.holoinsight.server.registry.grpc.agent.CollectTask> getCollectTasksList() {
    return collectTasks_;
  }

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  public java.util.List<? extends io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder> getCollectTasksOrBuilderList() {
    return collectTasks_;
  }

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  public int getCollectTasksCount() {
    return collectTasks_.size();
  }

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  public io.holoinsight.server.registry.grpc.agent.CollectTask getCollectTasks(int index) {
    return collectTasks_.get(index);
  }

  /**
   * <pre>
   * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
   * </pre>
   *
   * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
   */
  public io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder getCollectTasksOrBuilder(
      int index) {
    return collectTasks_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
    }
    for (int i = 0; i < collectTasks_.size(); i++) {
      output.writeMessage(2, collectTasks_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (!getStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
    }
    for (int i = 0; i < collectTasks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, collectTasks_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket)) {
      return super.equals(obj);
    }
    io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket other =
        (io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket) obj;

    if (!getState().equals(other.getState()))
      return false;
    if (!getCollectTasksList().equals(other.getCollectTasksList()))
      return false;
    if (!unknownFields.equals(other.unknownFields))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + getState().hashCode();
    if (getCollectTasksCount() > 0) {
      hash = (37 * hash) + COLLECT_TASKS_FIELD_NUMBER;
      hash = (53 * hash) + getCollectTasksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket)
      io.holoinsight.server.registry.grpc.agent.CollectConfigsBucketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_CollectConfigsBucket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_CollectConfigsBucket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket.class,
              io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket.Builder.class);
    }

    // Construct using io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getCollectTasksFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      state_ = "";

      if (collectTasksBuilder_ == null) {
        collectTasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        collectTasksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.holoinsight.server.registry.grpc.agent.RegistryForAgentProtos.internal_static_io_holoinsight_server_registry_grpc_agent_CollectConfigsBucket_descriptor;
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket getDefaultInstanceForType() {
      return io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket.getDefaultInstance();
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket build() {
      io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket buildPartial() {
      io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket result =
          new io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket(this);
      result.state_ = state_;
      if (collectTasksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          collectTasks_ = java.util.Collections.unmodifiableList(collectTasks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.collectTasks_ = collectTasks_;
      } else {
        result.collectTasks_ = collectTasksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket) {
        return mergeFrom((io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket other) {
      if (other == io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket
          .getDefaultInstance())
        return this;
      if (!other.getState().isEmpty()) {
        state_ = other.state_;
        onChanged();
      }
      if (collectTasksBuilder_ == null) {
        if (!other.collectTasks_.isEmpty()) {
          if (collectTasks_.isEmpty()) {
            collectTasks_ = other.collectTasks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCollectTasksIsMutable();
            collectTasks_.addAll(other.collectTasks_);
          }
          onChanged();
        }
      } else {
        if (!other.collectTasks_.isEmpty()) {
          if (collectTasksBuilder_.isEmpty()) {
            collectTasksBuilder_.dispose();
            collectTasksBuilder_ = null;
            collectTasks_ = other.collectTasks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            collectTasksBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                ? getCollectTasksFieldBuilder()
                : null;
          } else {
            collectTasksBuilder_.addAllMessages(other.collectTasks_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket) e
            .getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object state_ = "";

    /**
     * <pre>
     * 该bucket的状态
     * </pre>
     *
     * <code>string state = 1;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     * 该bucket的状态
     * </pre>
     *
     * <code>string state = 1;</code>
     */
    public com.google.protobuf.ByteString getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * 该bucket的状态
     * </pre>
     *
     * <code>string state = 1;</code>
     */
    public Builder setState(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      state_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 该bucket的状态
     * </pre>
     *
     * <code>string state = 1;</code>
     */
    public Builder clearState() {

      state_ = getDefaultInstance().getState();
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 该bucket的状态
     * </pre>
     *
     * <code>string state = 1;</code>
     */
    public Builder setStateBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      state_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.holoinsight.server.registry.grpc.agent.CollectTask> collectTasks_ =
        java.util.Collections.emptyList();

    private void ensureCollectTasksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        collectTasks_ =
            new java.util.ArrayList<io.holoinsight.server.registry.grpc.agent.CollectTask>(
                collectTasks_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<io.holoinsight.server.registry.grpc.agent.CollectTask, io.holoinsight.server.registry.grpc.agent.CollectTask.Builder, io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder> collectTasksBuilder_;

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public java.util.List<io.holoinsight.server.registry.grpc.agent.CollectTask> getCollectTasksList() {
      if (collectTasksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(collectTasks_);
      } else {
        return collectTasksBuilder_.getMessageList();
      }
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public int getCollectTasksCount() {
      if (collectTasksBuilder_ == null) {
        return collectTasks_.size();
      } else {
        return collectTasksBuilder_.getCount();
      }
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public io.holoinsight.server.registry.grpc.agent.CollectTask getCollectTasks(int index) {
      if (collectTasksBuilder_ == null) {
        return collectTasks_.get(index);
      } else {
        return collectTasksBuilder_.getMessage(index);
      }
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder setCollectTasks(int index,
        io.holoinsight.server.registry.grpc.agent.CollectTask value) {
      if (collectTasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCollectTasksIsMutable();
        collectTasks_.set(index, value);
        onChanged();
      } else {
        collectTasksBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder setCollectTasks(int index,
        io.holoinsight.server.registry.grpc.agent.CollectTask.Builder builderForValue) {
      if (collectTasksBuilder_ == null) {
        ensureCollectTasksIsMutable();
        collectTasks_.set(index, builderForValue.build());
        onChanged();
      } else {
        collectTasksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder addCollectTasks(io.holoinsight.server.registry.grpc.agent.CollectTask value) {
      if (collectTasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCollectTasksIsMutable();
        collectTasks_.add(value);
        onChanged();
      } else {
        collectTasksBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder addCollectTasks(int index,
        io.holoinsight.server.registry.grpc.agent.CollectTask value) {
      if (collectTasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCollectTasksIsMutable();
        collectTasks_.add(index, value);
        onChanged();
      } else {
        collectTasksBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder addCollectTasks(
        io.holoinsight.server.registry.grpc.agent.CollectTask.Builder builderForValue) {
      if (collectTasksBuilder_ == null) {
        ensureCollectTasksIsMutable();
        collectTasks_.add(builderForValue.build());
        onChanged();
      } else {
        collectTasksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder addCollectTasks(int index,
        io.holoinsight.server.registry.grpc.agent.CollectTask.Builder builderForValue) {
      if (collectTasksBuilder_ == null) {
        ensureCollectTasksIsMutable();
        collectTasks_.add(index, builderForValue.build());
        onChanged();
      } else {
        collectTasksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder addAllCollectTasks(
        java.lang.Iterable<? extends io.holoinsight.server.registry.grpc.agent.CollectTask> values) {
      if (collectTasksBuilder_ == null) {
        ensureCollectTasksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, collectTasks_);
        onChanged();
      } else {
        collectTasksBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder clearCollectTasks() {
      if (collectTasksBuilder_ == null) {
        collectTasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        collectTasksBuilder_.clear();
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public Builder removeCollectTasks(int index) {
      if (collectTasksBuilder_ == null) {
        ensureCollectTasksIsMutable();
        collectTasks_.remove(index);
        onChanged();
      } else {
        collectTasksBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public io.holoinsight.server.registry.grpc.agent.CollectTask.Builder getCollectTasksBuilder(
        int index) {
      return getCollectTasksFieldBuilder().getBuilder(index);
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder getCollectTasksOrBuilder(
        int index) {
      if (collectTasksBuilder_ == null) {
        return collectTasks_.get(index);
      } else {
        return collectTasksBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public java.util.List<? extends io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder> getCollectTasksOrBuilderList() {
      if (collectTasksBuilder_ != null) {
        return collectTasksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(collectTasks_);
      }
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public io.holoinsight.server.registry.grpc.agent.CollectTask.Builder addCollectTasksBuilder() {
      return getCollectTasksFieldBuilder()
          .addBuilder(io.holoinsight.server.registry.grpc.agent.CollectTask.getDefaultInstance());
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public io.holoinsight.server.registry.grpc.agent.CollectTask.Builder addCollectTasksBuilder(
        int index) {
      return getCollectTasksFieldBuilder().addBuilder(index,
          io.holoinsight.server.registry.grpc.agent.CollectTask.getDefaultInstance());
    }

    /**
     * <pre>
     * 属于该bucket的所有采集任务, 如果state与请求里的相同, 那么说明没有变化, 此时tasks为空
     * </pre>
     *
     * <code>repeated .io.holoinsight.server.registry.grpc.agent.CollectTask collect_tasks = 2;</code>
     */
    public java.util.List<io.holoinsight.server.registry.grpc.agent.CollectTask.Builder> getCollectTasksBuilderList() {
      return getCollectTasksFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<io.holoinsight.server.registry.grpc.agent.CollectTask, io.holoinsight.server.registry.grpc.agent.CollectTask.Builder, io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder> getCollectTasksFieldBuilder() {
      if (collectTasksBuilder_ == null) {
        collectTasksBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<io.holoinsight.server.registry.grpc.agent.CollectTask, io.holoinsight.server.registry.grpc.agent.CollectTask.Builder, io.holoinsight.server.registry.grpc.agent.CollectTaskOrBuilder>(
                collectTasks_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
        collectTasks_ = null;
      }
      return collectTasksBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket)
  }

  // @@protoc_insertion_point(class_scope:io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket)
  private static final io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket();
  }

  public static io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CollectConfigsBucket> PARSER =
      new com.google.protobuf.AbstractParser<CollectConfigsBucket>() {
        @java.lang.Override
        public CollectConfigsBucket parsePartialFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CollectConfigsBucket(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<CollectConfigsBucket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CollectConfigsBucket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.holoinsight.server.registry.grpc.agent.CollectConfigsBucket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
