/*
 * Copyright 2022 Holoinsight Project Authors. Licensed under Apache-2.0.
 */
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

package io.holoinsight.server.common.grpc;

public interface CommonResponseHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.holoinsight.server.common.grpc.CommonResponseHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();

  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString getMessageBytes();
}
