CREATE TABLE `alert_notify_record` (
                                       `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                       `history_id` BIGINT DEFAULT NULL COMMENT '历史id',
                                       `history_detail_id` BIGINT DEFAULT NULL COMMENT '历史详情id',
                                       `unique_id` VARCHAR ( 64 ) DEFAULT NULL,
                                       `rule_name` VARCHAR ( 255 ) DEFAULT NULL COMMENT '告警规则名称',
                                       `gmt_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP comment '创建时间',
                                       `gmt_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '修改时间',
                                       `notify_error_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '告警异常时间',
                                       `is_success` TINYINT NOT NULL COMMENT '告警是否成功',
                                       `notify_channel` VARCHAR ( 255 ) DEFAULT NULL COMMENT '通知渠道',
                                       `notify_error_node` LONGTEXT DEFAULT NULL COMMENT '通知异常节点',
                                       `notify_user` TEXT DEFAULT NULL COMMENT '通知人信息',
                                       `tenant` VARCHAR ( 64 ) DEFAULT NULL COMMENT '租户',
                                       `extra` LONGTEXT DEFAULT NULL COMMENT '额外信息',
                                       `trigger_result` LONGTEXT DEFAULT NULL COMMENT '告警计算信息',
                                       `env_type` VARCHAR ( 255 ) DEFAULT NULL COMMENT '运行环境',
                                       `workspace` VARCHAR ( 64 ) DEFAULT NULL,
                                       PRIMARY KEY ( `id` ),
                                       INDEX ( `history_detail_id` ),
                                       INDEX ( `history_id` ),
                                       INDEX ( `unique_id` )) ENGINE = INNODB COMMENT = '告警通知记录';