name: Integration Testing

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  IntegrationTesting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Print docker version
      if: ( runner.debug == '1' )
      shell: bash
      run: |
        docker version
        docker-compose version
    - name: Build docker image
      run: sh ./scripts/docker/build.sh
    - name: Deploy dependencies and server
      shell: bash
      run: |
        set -e
        sed -i '/pull_policy/g' ./deploy/examples/docker-compose/docker-compose.yaml 
        sh ./deploy/examples/docker-compose/up.sh
    - name: Run Integration Test
      shell: bash
      run: |
        echo TODO impl Integration Test here
